/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class ACpyComando extends PComando
{
    private PVar _var_;
    private TRecebe _recebe_;
    private PExp _exp_;
    private TPpv _ppv_;

    public ACpyComando()
    {
        // Constructor
    }

    public ACpyComando(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") TRecebe _recebe_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TPpv _ppv_)
    {
        // Constructor
        setVar(_var_);

        setRecebe(_recebe_);

        setExp(_exp_);

        setPpv(_ppv_);

    }

    @Override
    public Object clone()
    {
        return new ACpyComando(
            cloneNode(this._var_),
            cloneNode(this._recebe_),
            cloneNode(this._exp_),
            cloneNode(this._ppv_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACpyComando(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TRecebe getRecebe()
    {
        return this._recebe_;
    }

    public void setRecebe(TRecebe node)
    {
        if(this._recebe_ != null)
        {
            this._recebe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._recebe_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TPpv getPpv()
    {
        return this._ppv_;
    }

    public void setPpv(TPpv node)
    {
        if(this._ppv_ != null)
        {
            this._ppv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ppv_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._recebe_)
            + toString(this._exp_)
            + toString(this._ppv_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._recebe_ == child)
        {
            this._recebe_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._ppv_ == child)
        {
            this._ppv_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._recebe_ == oldChild)
        {
            setRecebe((TRecebe) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._ppv_ == oldChild)
        {
            setPpv((TPpv) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
