/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import java.util.*;
import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracaoDeclaracao extends PDeclaracao
{
    private PTipo _tipo_;
    private final LinkedList<TId> _idList_ = new LinkedList<TId>();

    public ADeclaracaoDeclaracao()
    {
        // Constructor
    }

    public ADeclaracaoDeclaracao(
        @SuppressWarnings("hiding") PTipo _tipo_,
        @SuppressWarnings("hiding") List<?> _idList_)
    {
        // Constructor
        setTipo(_tipo_);

        setIdList(_idList_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracaoDeclaracao(
            cloneNode(this._tipo_),
            cloneList(this._idList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracaoDeclaracao(this);
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public LinkedList<TId> getIdList()
    {
        return this._idList_;
    }

    public void setIdList(List<?> list)
    {
        for(TId e : this._idList_)
        {
            e.parent(null);
        }
        this._idList_.clear();

        for(Object obj_e : list)
        {
            TId e = (TId) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._idList_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipo_)
            + toString(this._idList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._idList_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        for(ListIterator<TId> i = this._idList_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TId) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
