/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class AElseOtherwise extends POtherwise
{
    private PCmd _cmd_;

    public AElseOtherwise()
    {
        // Constructor
    }

    public AElseOtherwise(
        @SuppressWarnings("hiding") PCmd _cmd_)
    {
        // Constructor
        setCmd(_cmd_);

    }

    @Override
    public Object clone()
    {
        return new AElseOtherwise(
            cloneNode(this._cmd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseOtherwise(this);
    }

    public PCmd getCmd()
    {
        return this._cmd_;
    }

    public void setCmd(PCmd node)
    {
        if(this._cmd_ != null)
        {
            this._cmd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cmd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cmd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cmd_ == child)
        {
            this._cmd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cmd_ == oldChild)
        {
            setCmd((PCmd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
