/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class AExpCompExp extends PExp
{
    private PExpComp _expComp_;

    public AExpCompExp()
    {
        // Constructor
    }

    public AExpCompExp(
        @SuppressWarnings("hiding") PExpComp _expComp_)
    {
        // Constructor
        setExpComp(_expComp_);

    }

    @Override
    public Object clone()
    {
        return new AExpCompExp(
            cloneNode(this._expComp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpCompExp(this);
    }

    public PExpComp getExpComp()
    {
        return this._expComp_;
    }

    public void setExpComp(PExpComp node)
    {
        if(this._expComp_ != null)
        {
            this._expComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expComp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expComp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expComp_ == child)
        {
            this._expComp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expComp_ == oldChild)
        {
            setExpComp((PExpComp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
