/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class AExpAtribExp extends PExp
{
    private PExpAtrib _expAtrib_;

    public AExpAtribExp()
    {
        // Constructor
    }

    public AExpAtribExp(
        @SuppressWarnings("hiding") PExpAtrib _expAtrib_)
    {
        // Constructor
        setExpAtrib(_expAtrib_);

    }

    @Override
    public Object clone()
    {
        return new AExpAtribExp(
            cloneNode(this._expAtrib_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpAtribExp(this);
    }

    public PExpAtrib getExpAtrib()
    {
        return this._expAtrib_;
    }

    public void setExpAtrib(PExpAtrib node)
    {
        if(this._expAtrib_ != null)
        {
            this._expAtrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAtrib_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expAtrib_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expAtrib_ == child)
        {
            this._expAtrib_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expAtrib_ == oldChild)
        {
            setExpAtrib((PExpAtrib) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
