/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class AIfComando extends PComando
{
    private TIn _in_;
    private TCase _case_;
    private TThat _that_;
    private PExp _exp_;
    private TDo _do_;
    private PCmd _cmd_;
    private POtherwise _otherwise_;

    public AIfComando()
    {
        // Constructor
    }

    public AIfComando(
        @SuppressWarnings("hiding") TIn _in_,
        @SuppressWarnings("hiding") TCase _case_,
        @SuppressWarnings("hiding") TThat _that_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TDo _do_,
        @SuppressWarnings("hiding") PCmd _cmd_,
        @SuppressWarnings("hiding") POtherwise _otherwise_)
    {
        // Constructor
        setIn(_in_);

        setCase(_case_);

        setThat(_that_);

        setExp(_exp_);

        setDo(_do_);

        setCmd(_cmd_);

        setOtherwise(_otherwise_);

    }

    @Override
    public Object clone()
    {
        return new AIfComando(
            cloneNode(this._in_),
            cloneNode(this._case_),
            cloneNode(this._that_),
            cloneNode(this._exp_),
            cloneNode(this._do_),
            cloneNode(this._cmd_),
            cloneNode(this._otherwise_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfComando(this);
    }

    public TIn getIn()
    {
        return this._in_;
    }

    public void setIn(TIn node)
    {
        if(this._in_ != null)
        {
            this._in_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._in_ = node;
    }

    public TCase getCase()
    {
        return this._case_;
    }

    public void setCase(TCase node)
    {
        if(this._case_ != null)
        {
            this._case_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._case_ = node;
    }

    public TThat getThat()
    {
        return this._that_;
    }

    public void setThat(TThat node)
    {
        if(this._that_ != null)
        {
            this._that_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._that_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TDo getDo()
    {
        return this._do_;
    }

    public void setDo(TDo node)
    {
        if(this._do_ != null)
        {
            this._do_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._do_ = node;
    }

    public PCmd getCmd()
    {
        return this._cmd_;
    }

    public void setCmd(PCmd node)
    {
        if(this._cmd_ != null)
        {
            this._cmd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cmd_ = node;
    }

    public POtherwise getOtherwise()
    {
        return this._otherwise_;
    }

    public void setOtherwise(POtherwise node)
    {
        if(this._otherwise_ != null)
        {
            this._otherwise_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._otherwise_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._in_)
            + toString(this._case_)
            + toString(this._that_)
            + toString(this._exp_)
            + toString(this._do_)
            + toString(this._cmd_)
            + toString(this._otherwise_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._in_ == child)
        {
            this._in_ = null;
            return;
        }

        if(this._case_ == child)
        {
            this._case_ = null;
            return;
        }

        if(this._that_ == child)
        {
            this._that_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._do_ == child)
        {
            this._do_ = null;
            return;
        }

        if(this._cmd_ == child)
        {
            this._cmd_ = null;
            return;
        }

        if(this._otherwise_ == child)
        {
            this._otherwise_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._in_ == oldChild)
        {
            setIn((TIn) newChild);
            return;
        }

        if(this._case_ == oldChild)
        {
            setCase((TCase) newChild);
            return;
        }

        if(this._that_ == oldChild)
        {
            setThat((TThat) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._do_ == oldChild)
        {
            setDo((TDo) newChild);
            return;
        }

        if(this._cmd_ == oldChild)
        {
            setCmd((PCmd) newChild);
            return;
        }

        if(this._otherwise_ == oldChild)
        {
            setOtherwise((POtherwise) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
