/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class AOtherwiseComando extends PComando
{
    private POtherwise _otherwise_;

    public AOtherwiseComando()
    {
        // Constructor
    }

    public AOtherwiseComando(
        @SuppressWarnings("hiding") POtherwise _otherwise_)
    {
        // Constructor
        setOtherwise(_otherwise_);

    }

    @Override
    public Object clone()
    {
        return new AOtherwiseComando(
            cloneNode(this._otherwise_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOtherwiseComando(this);
    }

    public POtherwise getOtherwise()
    {
        return this._otherwise_;
    }

    public void setOtherwise(POtherwise node)
    {
        if(this._otherwise_ != null)
        {
            this._otherwise_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._otherwise_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._otherwise_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._otherwise_ == child)
        {
            this._otherwise_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._otherwise_ == oldChild)
        {
            setOtherwise((POtherwise) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
