/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AIfElseInCaseThat extends PInCaseThat
{
    private PInCaseThat _inCaseThat_;

    public AIfElseInCaseThat()
    {
        // Constructor
    }

    public AIfElseInCaseThat(
        @SuppressWarnings("hiding") PInCaseThat _inCaseThat_)
    {
        // Constructor
        setInCaseThat(_inCaseThat_);

    }

    @Override
    public Object clone()
    {
        return new AIfElseInCaseThat(
            cloneNode(this._inCaseThat_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfElseInCaseThat(this);
    }

    public PInCaseThat getInCaseThat()
    {
        return this._inCaseThat_;
    }

    public void setInCaseThat(PInCaseThat node)
    {
        if(this._inCaseThat_ != null)
        {
            this._inCaseThat_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inCaseThat_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inCaseThat_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inCaseThat_ == child)
        {
            this._inCaseThat_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inCaseThat_ == oldChild)
        {
            setInCaseThat((PInCaseThat) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
