/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AIfElseComando extends PComando
{
    private PIf _left_;
    private TElse _else_;
    private PComando _right_;

    public AIfElseComando()
    {
        // Constructor
    }

    public AIfElseComando(
        @SuppressWarnings("hiding") PIf _left_,
        @SuppressWarnings("hiding") TElse _else_,
        @SuppressWarnings("hiding") PComando _right_)
    {
        // Constructor
        setLeft(_left_);

        setElse(_else_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AIfElseComando(
            cloneNode(this._left_),
            cloneNode(this._else_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfElseComando(this);
    }

    public PIf getLeft()
    {
        return this._left_;
    }

    public void setLeft(PIf node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TElse getElse()
    {
        return this._else_;
    }

    public void setElse(TElse node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    public PComando getRight()
    {
        return this._right_;
    }

    public void setRight(PComando node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._else_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PIf) newChild);
            return;
        }

        if(this._else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
