/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMultiPos extends PMultiPos
{
    private TLCol _lCol_;
    private PExp _exp_;
    private TRCol _rCol_;

    public AMultiPos()
    {
        // Constructor
    }

    public AMultiPos(
        @SuppressWarnings("hiding") TLCol _lCol_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TRCol _rCol_)
    {
        // Constructor
        setLCol(_lCol_);

        setExp(_exp_);

        setRCol(_rCol_);

    }

    @Override
    public Object clone()
    {
        return new AMultiPos(
            cloneNode(this._lCol_),
            cloneNode(this._exp_),
            cloneNode(this._rCol_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiPos(this);
    }

    public TLCol getLCol()
    {
        return this._lCol_;
    }

    public void setLCol(TLCol node)
    {
        if(this._lCol_ != null)
        {
            this._lCol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lCol_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TRCol getRCol()
    {
        return this._rCol_;
    }

    public void setRCol(TRCol node)
    {
        if(this._rCol_ != null)
        {
            this._rCol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rCol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lCol_)
            + toString(this._exp_)
            + toString(this._rCol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lCol_ == child)
        {
            this._lCol_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._rCol_ == child)
        {
            this._rCol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lCol_ == oldChild)
        {
            setLCol((TLCol) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._rCol_ == oldChild)
        {
            setRCol((TRCol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
